name: Publish to PyPI.org
on:
  release:
    types: [published]
  
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Install python and build package
        uses: actions/setup-python@v4
      - run: python3 -m pip install --upgrade build && python3 -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}